from rdkit import Chem
from rdkit.Chem import Descriptors
import pandas as pd


def calculate_descriptors(NAME,smiles,df):
    # 读取分子文件
    mol = Chem.MolFromSmiles(smiles)

    # 提取药物特征
    BalabanJ = Descriptors.BalabanJ(mol)
    BertzCT = Descriptors.BertzCT(mol)
    Chi0 = Descriptors.Chi0(mol)
    Chi0n = Descriptors.Chi0n(mol)
    Chi0v = Descriptors.Chi0v(mol)
    Chi1 = Descriptors.Chi1(mol)
    Chi1n = Descriptors.Chi1n(mol)
    Chi1v = Descriptors.Chi1v(mol)
    Chi2n = Descriptors.Chi2n(mol)
    Chi2v = Descriptors.Chi2v(mol)
    Chi3n = Descriptors.Chi3n(mol)
    Chi3v = Descriptors.Chi3v(mol)
    Chi4n = Descriptors.Chi4n(mol)
    Chi4v = Descriptors.Chi4v(mol)
    EState_VSA1 = Descriptors.EState_VSA1(mol)
    EState_VSA10 = Descriptors.EState_VSA10(mol)
    EState_VSA11 = Descriptors.EState_VSA11(mol)
    EState_VSA2 = Descriptors.EState_VSA2(mol)
    EState_VSA3 = Descriptors.EState_VSA3(mol)
    EState_VSA4 = Descriptors.EState_VSA4(mol)
    EState_VSA5 = Descriptors.EState_VSA5(mol)
    EState_VSA6 = Descriptors.EState_VSA6(mol)
    EState_VSA7 = Descriptors.EState_VSA7(mol)
    EState_VSA8 = Descriptors.EState_VSA8(mol)
    EState_VSA9 = Descriptors.EState_VSA9(mol)
    ExactMolWt = Descriptors.ExactMolWt(mol)
    FpDensityMorgan1 = Descriptors.FpDensityMorgan1(mol)
    FpDensityMorgan2 = Descriptors.FpDensityMorgan2(mol)
    FpDensityMorgan3 = Descriptors.FpDensityMorgan3(mol)
    FractionCSP3 = Descriptors.FractionCSP3(mol)
    HallKierAlpha = Descriptors.HallKierAlpha(mol)
    HeavyAtomCount = Descriptors.HeavyAtomCount(mol)
    HeavyAtomMolWt = Descriptors.HeavyAtomMolWt(mol)
    Ipc = Descriptors.Ipc(mol)
    Kappa1 = Descriptors.Kappa1(mol)
    Kappa2 = Descriptors.Kappa2(mol)
    Kappa3 = Descriptors.Kappa3(mol)
    LabuteASA = Descriptors.LabuteASA(mol)
    MaxAbsEStateIndex = Descriptors.MaxAbsEStateIndex(mol)
    MaxAbsPartialCharge = Descriptors.MaxAbsPartialCharge(mol)
    MaxEStateIndex = Descriptors.MaxEStateIndex(mol)
    MaxPartialCharge = Descriptors.MaxPartialCharge(mol)
    MinAbsEStateIndex = Descriptors.MinAbsEStateIndex(mol)
    MinAbsPartialCharge = Descriptors.MinAbsPartialCharge(mol)
    MinEStateIndex = Descriptors.MinEStateIndex(mol)
    MinPartialCharge = Descriptors.MinPartialCharge(mol)
    MolLogP = Descriptors.MolLogP(mol)
    MolMR = Descriptors.MolMR(mol)
    MolWt = Descriptors.MolWt(mol)
    NHOHCount = Descriptors.NHOHCount(mol)
    NOCount = Descriptors.NOCount(mol)
    NumAliphaticCarbocycles = Descriptors.NumAliphaticCarbocycles(mol)
    NumAliphaticHeterocycles = Descriptors.NumAliphaticHeterocycles(mol)
    NumAliphaticRings = Descriptors.NumAliphaticRings(mol)
    NumAromaticCarbocycles = Descriptors.NumAromaticCarbocycles(mol)
    NumAromaticHeterocycles = Descriptors.NumAromaticHeterocycles(mol)
    NumAromaticRings = Descriptors.NumAromaticRings(mol)
    NumHAcceptors = Descriptors.NumHAcceptors(mol)
    NumHDonors = Descriptors.NumHDonors(mol)
    NumHeteroatoms = Descriptors.NumHeteroatoms(mol)
    NumRadicalElectrons = Descriptors.NumRadicalElectrons(mol)
    NumRotatableBonds = Descriptors.NumRotatableBonds(mol)
    NumSaturatedCarbocycles = Descriptors.NumSaturatedCarbocycles(mol)
    NumSaturatedHeterocycles = Descriptors.NumSaturatedHeterocycles(mol)
    NumSaturatedRings = Descriptors.NumSaturatedRings(mol)
    NumValenceElectrons = Descriptors.NumValenceElectrons(mol)
    PEOE_VSA1 = Descriptors.PEOE_VSA1(mol)
    PEOE_VSA10 = Descriptors.PEOE_VSA10(mol)
    PEOE_VSA11 = Descriptors.PEOE_VSA11(mol)
    PEOE_VSA12 = Descriptors.PEOE_VSA12(mol)
    PEOE_VSA13 = Descriptors.PEOE_VSA13(mol)
    PEOE_VSA14 = Descriptors.PEOE_VSA14(mol)
    PEOE_VSA2 = Descriptors.PEOE_VSA2(mol)
    PEOE_VSA3 = Descriptors.PEOE_VSA3(mol)
    PEOE_VSA4 = Descriptors.PEOE_VSA4(mol)
    PEOE_VSA5 = Descriptors.PEOE_VSA5(mol)
    PEOE_VSA6 = Descriptors.PEOE_VSA6(mol)
    PEOE_VSA7 = Descriptors.PEOE_VSA7(mol)
    PEOE_VSA8 = Descriptors.PEOE_VSA8(mol)
    PEOE_VSA9 = Descriptors.PEOE_VSA9(mol)
    RingCount = Descriptors.RingCount(mol)
    SMR_VSA1 = Descriptors.SMR_VSA1(mol)
    SMR_VSA10 = Descriptors.SMR_VSA10(mol)
    SMR_VSA2 = Descriptors.SMR_VSA2(mol)
    SMR_VSA3 = Descriptors.SMR_VSA3(mol)
    SMR_VSA4 = Descriptors.SMR_VSA4(mol)
    SMR_VSA5 = Descriptors.SMR_VSA5(mol)
    SMR_VSA6 = Descriptors.SMR_VSA6(mol)
    SMR_VSA7 = Descriptors.SMR_VSA7(mol)
    SMR_VSA8 = Descriptors.SMR_VSA8(mol)
    SMR_VSA9 = Descriptors.SMR_VSA9(mol)
    SlogP_VSA1 = Descriptors.SlogP_VSA1(mol)
    SlogP_VSA10 = Descriptors.SlogP_VSA10(mol)
    SlogP_VSA11 = Descriptors.SlogP_VSA11(mol)
    SlogP_VSA12 = Descriptors.SlogP_VSA12(mol)
    SlogP_VSA2 = Descriptors.SlogP_VSA2(mol)
    SlogP_VSA3 = Descriptors.SlogP_VSA3(mol)
    SlogP_VSA4 = Descriptors.SlogP_VSA4(mol)
    SlogP_VSA5 = Descriptors.SlogP_VSA5(mol)
    SlogP_VSA6 = Descriptors.SlogP_VSA6(mol)
    SlogP_VSA7 = Descriptors.SlogP_VSA7(mol)
    SlogP_VSA8 = Descriptors.SlogP_VSA8(mol)
    SlogP_VSA9 = Descriptors.SlogP_VSA9(mol)
    TPSA = Descriptors.TPSA(mol)
    VSA_EState1 = Descriptors.VSA_EState1(mol)
    VSA_EState10 = Descriptors.VSA_EState10(mol)
    VSA_EState2 = Descriptors.VSA_EState2(mol)
    VSA_EState3 = Descriptors.VSA_EState3(mol)
    VSA_EState4 = Descriptors.VSA_EState4(mol)
    VSA_EState5 = Descriptors.VSA_EState5(mol)
    VSA_EState6 = Descriptors.VSA_EState6(mol)
    VSA_EState7 = Descriptors.VSA_EState7(mol)
    VSA_EState8 = Descriptors.VSA_EState8(mol)
    VSA_EState9 = Descriptors.VSA_EState9(mol)
    fr_Al_COO = Descriptors.fr_Al_COO(mol)
    fr_Al_OH = Descriptors.fr_Al_OH(mol)
    fr_Al_OH_noTert = Descriptors.fr_Al_OH_noTert(mol)
    fr_ArN = Descriptors.fr_ArN(mol)
    fr_Ar_COO = Descriptors.fr_Ar_COO(mol)
    fr_Ar_N = Descriptors.fr_Ar_N(mol)
    fr_Ar_NH = Descriptors.fr_Ar_NH(mol)
    fr_Ar_OH = Descriptors.fr_Ar_OH(mol)
    fr_COO = Descriptors.fr_COO(mol)
    fr_COO2 = Descriptors.fr_COO2(mol)
    fr_C_O = Descriptors.fr_C_O(mol)
    fr_C_O_noCOO = Descriptors.fr_C_O_noCOO(mol)
    fr_C_S = Descriptors.fr_C_S(mol)
    fr_HOCCN = Descriptors.fr_HOCCN(mol)
    fr_Imine = Descriptors.fr_Imine(mol)
    fr_NH0 = Descriptors.fr_NH0(mol)
    fr_NH1 = Descriptors.fr_NH1(mol)
    fr_NH2 = Descriptors.fr_NH2(mol)
    fr_N_O = Descriptors.fr_N_O(mol)
    fr_Ndealkylation1 = Descriptors.fr_Ndealkylation1(mol)
    fr_Ndealkylation2 = Descriptors.fr_Ndealkylation2(mol)
    fr_Nhpyrrole = Descriptors.fr_Nhpyrrole(mol)
    fr_SH = Descriptors.fr_SH(mol)
    fr_aldehyde = Descriptors.fr_aldehyde(mol)
    fr_alkyl_carbamate = Descriptors.fr_alkyl_carbamate(mol)
    fr_alkyl_halide = Descriptors.fr_alkyl_halide(mol)
    fr_allylic_oxid = Descriptors.fr_allylic_oxid(mol)
    fr_amide = Descriptors.fr_amide(mol)
    fr_amidine = Descriptors.fr_amidine(mol)
    fr_aniline = Descriptors.fr_aniline(mol)
    fr_aryl_methyl = Descriptors.fr_aryl_methyl(mol)
    fr_azide = Descriptors.fr_azide(mol)
    fr_azo = Descriptors.fr_azo(mol)
    fr_barbitur = Descriptors.fr_barbitur(mol)
    fr_benzene = Descriptors.fr_benzene(mol)
    fr_benzodiazepine = Descriptors.fr_benzodiazepine(mol)
    fr_bicyclic = Descriptors.fr_bicyclic(mol)
    fr_diazo = Descriptors.fr_diazo(mol)
    fr_dihydropyridine = Descriptors.fr_dihydropyridine(mol)
    fr_epoxide = Descriptors.fr_epoxide(mol)
    fr_ester = Descriptors.fr_ester(mol)
    fr_ether = Descriptors.fr_ether(mol)
    fr_furan = Descriptors.fr_furan(mol)
    fr_guanido = Descriptors.fr_guanido(mol)
    fr_halogen = Descriptors.fr_halogen(mol)
    fr_hdrzine = Descriptors.fr_hdrzine(mol)
    fr_hdrzone = Descriptors.fr_hdrzone(mol)
    fr_imidazole = Descriptors.fr_imidazole(mol)
    fr_imide = Descriptors.fr_imide(mol)
    fr_isocyan = Descriptors.fr_isocyan(mol)
    fr_isothiocyan = Descriptors.fr_isothiocyan(mol)
    fr_ketone = Descriptors.fr_ketone(mol)
    fr_ketone_Topliss = Descriptors.fr_ketone_Topliss(mol)
    fr_lactam = Descriptors.fr_lactam(mol)
    fr_lactone = Descriptors.fr_lactone(mol)
    fr_methoxy = Descriptors.fr_methoxy(mol)
    fr_morpholine = Descriptors.fr_morpholine(mol)
    fr_nitrile = Descriptors.fr_nitrile(mol)
    fr_nitro = Descriptors.fr_nitro(mol)
    fr_nitro_arom = Descriptors.fr_nitro_arom(mol)
    fr_nitro_arom_nonortho = Descriptors.fr_nitro_arom_nonortho(mol)
    fr_nitroso = Descriptors.fr_nitroso(mol)
    fr_oxazole = Descriptors.fr_oxazole(mol)
    fr_oxime = Descriptors.fr_oxime(mol)
    fr_para_hydroxylation = Descriptors.fr_para_hydroxylation(mol)
    fr_phenol = Descriptors.fr_phenol(mol)
    fr_phenol_noOrthoHbond = Descriptors.fr_phenol_noOrthoHbond(mol)
    fr_phos_acid = Descriptors.fr_phos_acid(mol)
    fr_phos_ester = Descriptors.fr_phos_ester(mol)
    fr_piperdine = Descriptors.fr_piperdine(mol)
    fr_piperzine = Descriptors.fr_piperzine(mol)
    fr_priamide = Descriptors.fr_priamide(mol)
    fr_prisulfonamd = Descriptors.fr_prisulfonamd(mol)
    fr_pyridine = Descriptors.fr_pyridine(mol)
    fr_quatN = Descriptors.fr_quatN(mol)
    fr_sulfide = Descriptors.fr_sulfide(mol)
    fr_sulfonamd = Descriptors.fr_sulfonamd(mol)
    fr_sulfone = Descriptors.fr_sulfone(mol)
    fr_term_acetylene = Descriptors.fr_term_acetylene(mol)
    fr_tetrazole = Descriptors.fr_tetrazole(mol)
    fr_thiazole = Descriptors.fr_thiazole(mol)
    fr_thiocyan = Descriptors.fr_thiocyan(mol)
    fr_thiophene = Descriptors.fr_thiophene(mol)
    fr_unbrch_alkane = Descriptors.fr_unbrch_alkane(mol)
    fr_urea = Descriptors.fr_urea(mol)
    qed = Descriptors.qed(mol)
    Molecular_weight = Descriptors.MolWt(mol)
    LogP = Descriptors.MolLogP(mol)

    df = df._append({"NAME":NAME,"BalabanJ":BalabanJ, "BertzCT":BertzCT, "Chi0":Chi0, "Chi0n":Chi0n, "Chi0v":Chi0v, "Chi1":Chi1, "Chi1n":Chi1n, "Chi1v":Chi1v, "Chi2n":Chi2n, "Chi2v":Chi2v, "Chi3n":Chi3n, "Chi3v":Chi3v, "Chi4n":Chi4n, "Chi4v":Chi4v, "EState_VSA1":EState_VSA1, "EState_VSA10":EState_VSA10, "EState_VSA11":EState_VSA11, "EState_VSA2":EState_VSA2, "EState_VSA3":EState_VSA3, "EState_VSA4":EState_VSA4, "EState_VSA5":EState_VSA5, "EState_VSA6":EState_VSA6, "EState_VSA7":EState_VSA7, "EState_VSA8":EState_VSA8, "EState_VSA9":EState_VSA9, "ExactMolWt":ExactMolWt, "FpDensityMorgan1":FpDensityMorgan1, "FpDensityMorgan2":FpDensityMorgan2, "FpDensityMorgan3":FpDensityMorgan3, "FractionCSP3":FractionCSP3, "HallKierAlpha":HallKierAlpha, "HeavyAtomCount":HeavyAtomCount, "HeavyAtomMolWt":HeavyAtomMolWt, "Ipc":Ipc, "Kappa1":Kappa1, "Kappa2":Kappa2, "Kappa3":Kappa3, "LabuteASA":LabuteASA, "MaxAbsEStateIndex":MaxAbsEStateIndex, "MaxAbsPartialCharge":MaxAbsPartialCharge, "MaxEStateIndex":MaxEStateIndex, "MaxPartialCharge":MaxPartialCharge, "MinAbsEStateIndex":MinAbsEStateIndex, "MinAbsPartialCharge":MinAbsPartialCharge, "MinEStateIndex":MinEStateIndex, "MinPartialCharge":MinPartialCharge, "MolLogP":MolLogP, "MolMR":MolMR, "MolWt":MolWt, "NHOHCount":NHOHCount, "NOCount":NOCount, "NumAliphaticCarbocycles":NumAliphaticCarbocycles, "NumAliphaticHeterocycles":NumAliphaticHeterocycles, "NumAliphaticRings":NumAliphaticRings, "NumAromaticCarbocycles":NumAromaticCarbocycles, "NumAromaticHeterocycles":NumAromaticHeterocycles, "NumAromaticRings":NumAromaticRings, "NumHAcceptors":NumHAcceptors, "NumHDonors":NumHDonors, "NumHeteroatoms":NumHeteroatoms, "NumRadicalElectrons":NumRadicalElectrons, "NumRotatableBonds":NumRotatableBonds, "NumSaturatedCarbocycles":NumSaturatedCarbocycles, "NumSaturatedHeterocycles":NumSaturatedHeterocycles, "NumSaturatedRings":NumSaturatedRings, "NumValenceElectrons":NumValenceElectrons, "PEOE_VSA1":PEOE_VSA1, "PEOE_VSA10":PEOE_VSA10, "PEOE_VSA11":PEOE_VSA11, "PEOE_VSA12":PEOE_VSA12, "PEOE_VSA13":PEOE_VSA13, "PEOE_VSA14":PEOE_VSA14, "PEOE_VSA2":PEOE_VSA2, "PEOE_VSA3":PEOE_VSA3, "PEOE_VSA4":PEOE_VSA4, "PEOE_VSA5":PEOE_VSA5, "PEOE_VSA6":PEOE_VSA6, "PEOE_VSA7":PEOE_VSA7, "PEOE_VSA8":PEOE_VSA8, "PEOE_VSA9":PEOE_VSA9, "RingCount":RingCount, "SMR_VSA1":SMR_VSA1, "SMR_VSA10":SMR_VSA10, "SMR_VSA2":SMR_VSA2, "SMR_VSA3":SMR_VSA3, "SMR_VSA4":SMR_VSA4, "SMR_VSA5":SMR_VSA5, "SMR_VSA6":SMR_VSA6, "SMR_VSA7":SMR_VSA7, "SMR_VSA8":SMR_VSA8, "SMR_VSA9":SMR_VSA9, "SlogP_VSA1":SlogP_VSA1, "SlogP_VSA10":SlogP_VSA10, "SlogP_VSA11":SlogP_VSA11, "SlogP_VSA12":SlogP_VSA12, "SlogP_VSA2":SlogP_VSA2, "SlogP_VSA3":SlogP_VSA3, "SlogP_VSA4":SlogP_VSA4, "SlogP_VSA5":SlogP_VSA5, "SlogP_VSA6":SlogP_VSA6, "SlogP_VSA7":SlogP_VSA7, "SlogP_VSA8":SlogP_VSA8, "SlogP_VSA9":SlogP_VSA9, "TPSA":TPSA, "VSA_EState1":VSA_EState1, "VSA_EState10":VSA_EState10, "VSA_EState2":VSA_EState2, "VSA_EState3":VSA_EState3, "VSA_EState4":VSA_EState4, "VSA_EState5":VSA_EState5, "VSA_EState6":VSA_EState6, "VSA_EState7":VSA_EState7, "VSA_EState8":VSA_EState8, "VSA_EState9":VSA_EState9, "fr_Al_COO":fr_Al_COO, "fr_Al_OH":fr_Al_OH, "fr_Al_OH_noTert":fr_Al_OH_noTert, "fr_ArN":fr_ArN, "fr_Ar_COO":fr_Ar_COO, "fr_Ar_N":fr_Ar_N, "fr_Ar_NH":fr_Ar_NH, "fr_Ar_OH":fr_Ar_OH, "fr_COO":fr_COO, "fr_COO2":fr_COO2, "fr_C_O":fr_C_O, "fr_C_O_noCOO":fr_C_O_noCOO, "fr_C_S":fr_C_S, "fr_HOCCN":fr_HOCCN, "fr_Imine":fr_Imine, "fr_NH0":fr_NH0, "fr_NH1":fr_NH1, "fr_NH2":fr_NH2, "fr_N_O":fr_N_O, "fr_Ndealkylation1":fr_Ndealkylation1, "fr_Ndealkylation2":fr_Ndealkylation2, "fr_Nhpyrrole":fr_Nhpyrrole, "fr_SH":fr_SH, "fr_aldehyde":fr_aldehyde, "fr_alkyl_carbamate":fr_alkyl_carbamate, "fr_alkyl_halide":fr_alkyl_halide, "fr_allylic_oxid":fr_allylic_oxid, "fr_amide":fr_amide, "fr_amidine":fr_amidine, "fr_aniline":fr_aniline, "fr_aryl_methyl":fr_aryl_methyl, "fr_azide":fr_azide, "fr_azo":fr_azo, "fr_barbitur":fr_barbitur, "fr_benzene":fr_benzene, "fr_benzodiazepine":fr_benzodiazepine, "fr_bicyclic":fr_bicyclic, "fr_diazo":fr_diazo, "fr_dihydropyridine":fr_dihydropyridine, "fr_epoxide":fr_epoxide, "fr_ester":fr_ester, "fr_ether":fr_ether, "fr_furan":fr_furan, "fr_guanido":fr_guanido, "fr_halogen":fr_halogen, "fr_hdrzine":fr_hdrzine, "fr_hdrzone":fr_hdrzone, "fr_imidazole":fr_imidazole, "fr_imide":fr_imide, "fr_isocyan":fr_isocyan, "fr_isothiocyan":fr_isothiocyan, "fr_ketone":fr_ketone, "fr_ketone_Topliss":fr_ketone_Topliss, "fr_lactam":fr_lactam, "fr_lactone":fr_lactone, "fr_methoxy":fr_methoxy, "fr_morpholine":fr_morpholine, "fr_nitrile":fr_nitrile, "fr_nitro":fr_nitro, "fr_nitro_arom":fr_nitro_arom, "fr_nitro_arom_nonortho":fr_nitro_arom_nonortho, "fr_nitroso":fr_nitroso, "fr_oxazole":fr_oxazole, "fr_oxime":fr_oxime, "fr_para_hydroxylation":fr_para_hydroxylation, "fr_phenol":fr_phenol, "fr_phenol_noOrthoHbond":fr_phenol_noOrthoHbond, "fr_phos_acid":fr_phos_acid, "fr_phos_ester":fr_phos_ester, "fr_piperdine":fr_piperdine, "fr_piperzine":fr_piperzine, "fr_priamide":fr_priamide, "fr_prisulfonamd":fr_prisulfonamd, "fr_pyridine":fr_pyridine, "fr_quatN":fr_quatN, "fr_sulfide":fr_sulfide, "fr_sulfonamd":fr_sulfonamd, "fr_sulfone":fr_sulfone, "fr_term_acetylene":fr_term_acetylene, "fr_tetrazole":fr_tetrazole, "fr_thiazole":fr_thiazole, "fr_thiocyan":fr_thiocyan, "fr_thiophene":fr_thiophene, "fr_unbrch_alkane":fr_unbrch_alkane, "fr_urea":fr_urea, "qed":qed, "Molecular_weight":Molecular_weight, "LogP":LogP
}, ignore_index=True)
    return df


df = pd.DataFrame(columns=["NAME","BalabanJ", "BertzCT", "Chi0", "Chi0n", "Chi0v", "Chi1", "Chi1n", "Chi1v", "Chi2n", "Chi2v", "Chi3n", "Chi3v", "Chi4n", "Chi4v",
                           "EState_VSA1", "EState_VSA10", "EState_VSA11", "EState_VSA2", "EState_VSA3", "EState_VSA4", "EState_VSA5", "EState_VSA6", "EState_VSA7", "EState_VSA8", "EState_VSA9",
                           "ExactMolWt", "FpDensityMorgan1", "FpDensityMorgan2", "FpDensityMorgan3", "FractionCSP3", "HallKierAlpha", "HeavyAtomCount", "HeavyAtomMolWt", "Ipc",
                           "Kappa1", "Kappa2", "Kappa3", "LabuteASA",
                           "MaxAbsEStateIndex", "MaxAbsPartialCharge", "MaxEStateIndex", "MaxPartialCharge",
                           "MinAbsEStateIndex", "MinAbsPartialCharge", "MinEStateIndex", "MinPartialCharge",
                           "MolLogP", "MolMR", "MolWt", "NHOHCount", "NOCount",
                           "NumAliphaticCarbocycles", "NumAliphaticHeterocycles", "NumAliphaticRings", "NumAromaticCarbocycles", "NumAromaticHeterocycles", "NumAromaticRings",
                           "NumHAcceptors", "NumHDonors", "NumHeteroatoms", "NumRadicalElectrons", "NumRotatableBonds", "NumSaturatedCarbocycles", "NumSaturatedHeterocycles", "NumSaturatedRings", "NumValenceElectrons",
                           "PEOE_VSA1", "PEOE_VSA10", "PEOE_VSA11", "PEOE_VSA12", "PEOE_VSA13", "PEOE_VSA14", "PEOE_VSA2", "PEOE_VSA3", "PEOE_VSA4", "PEOE_VSA5", "PEOE_VSA6", "PEOE_VSA7", "PEOE_VSA8", "PEOE_VSA9",
                           "RingCount", "SMR_VSA1", "SMR_VSA10", "SMR_VSA2", "SMR_VSA3", "SMR_VSA4", "SMR_VSA5", "SMR_VSA6", "SMR_VSA7", "SMR_VSA8", "SMR_VSA9",
                           "SlogP_VSA1", "SlogP_VSA10", "SlogP_VSA11", "SlogP_VSA12", "SlogP_VSA2", "SlogP_VSA3", "SlogP_VSA4", "SlogP_VSA5", "SlogP_VSA6", "SlogP_VSA7", "SlogP_VSA8", "SlogP_VSA9",
                           "TPSA", "VSA_EState1", "VSA_EState10", "VSA_EState2", "VSA_EState3", "VSA_EState4", "VSA_EState5", "VSA_EState6", "VSA_EState7", "VSA_EState8", "VSA_EState9",
                           "fr_Al_COO", "fr_Al_OH", "fr_Al_OH_noTert", "fr_ArN", "fr_Ar_COO", "fr_Ar_N", "fr_Ar_NH", "fr_Ar_OH", "fr_COO", "fr_COO2",
                           "fr_C_O", "fr_C_O_noCOO", "fr_C_S", "fr_HOCCN", "fr_Imine", "fr_NH0", "fr_NH1", "fr_NH2", "fr_N_O",
                           "fr_Ndealkylation1", "fr_Ndealkylation2", "fr_Nhpyrrole", "fr_SH", "fr_aldehyde", "fr_alkyl_carbamate", "fr_alkyl_halide", "fr_allylic_oxid",
                           "fr_amide", "fr_amidine", "fr_aniline", "fr_aryl_methyl", "fr_azide", "fr_azo", "fr_barbitur", "fr_benzene", "fr_benzodiazepine", "fr_bicyclic",
                           "fr_diazo", "fr_dihydropyridine", "fr_epoxide", "fr_ester", "fr_ether", "fr_furan", "fr_guanido", "fr_halogen", "fr_hdrzine", "fr_hdrzone",
                           "fr_imidazole", "fr_imide", "fr_isocyan", "fr_isothiocyan", "fr_ketone", "fr_ketone_Topliss", "fr_lactam", "fr_lactone", "fr_methoxy", "fr_morpholine",
                           "fr_nitrile", "fr_nitro", "fr_nitro_arom", "fr_nitro_arom_nonortho", "fr_nitroso", "fr_oxazole", "fr_oxime", "fr_para_hydroxylation", "fr_phenol",
                           "fr_phenol_noOrthoHbond", "fr_phos_acid", "fr_phos_ester", "fr_piperdine", "fr_piperzine", "fr_priamide", "fr_prisulfonamd", "fr_pyridine", "fr_quatN",
                           "fr_sulfide", "fr_sulfonamd", "fr_sulfone", "fr_term_acetylene", "fr_tetrazole", "fr_thiazole", "fr_thiocyan", "fr_thiophene", "fr_unbrch_alkane",
                           "fr_urea", "qed", "Molecular_weight", "LogP"])

data1 = pd.read_csv("../data/drug_name.csv")
data2 = pd.read_csv("../data/drug_smiles.csv")
DBid = data1["NAME"]
smiles = data2["SMILES"]
for i in range(len(smiles)):
    df = calculate_descriptors(DBid[i],smiles[i],df)
    print(i+1)

df.to_csv("../feature/drug_phy_chem.csv", index=False)
print("物化性质特征维数：",df.shape[1]-1)